version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaSegura123!
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./cadastro-pedidos-backend
      dockerfile: CadastroPedidos.API/Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge